# Generated by Django 2.0.6 on 2018-07-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('pv', models.IntegerField(default=0, verbose_name='总浏览数')),
                ('uv', models.IntegerField(default=0, verbose_name='总用户浏览数')),
                ('uv_ip_json', models.TextField(null=True, verbose_name='用户ip的json数组')),
                ('lasted_at', models.DateTimeField(auto_now_add=True, verbose_name='最新修改时间')),
                ('browsed_at', models.DateTimeField(auto_now_add=True, verbose_name='最新浏览时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='BlogBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.IntegerField(default=0, verbose_name='浏览数')),
                ('uv', models.IntegerField(default=0, verbose_name='用户浏览数')),
                ('uv_ip_json', models.TextField(null=True, verbose_name='用户ip的json数组')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_file_name', models.CharField(max_length=500, null=True, verbose_name='源文件名')),
                ('content_type', models.CharField(max_length=50, verbose_name='类型')),
                ('size', models.IntegerField(null=True, verbose_name='文件大小')),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('save_path', models.CharField(max_length=1024, verbose_name='存储路径')),
                ('driver', models.CharField(default='local', max_length=50, verbose_name='驱动')),
                ('used_at', models.DateTimeField(null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限名')),
                ('controller', models.CharField(max_length=100, verbose_name='权限对应控制器')),
                ('mothod', models.CharField(max_length=200, verbose_name='权限对应方法')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('salt', models.CharField(max_length=5, verbose_name='密码随机字符串加密')),
                ('lasted_at', models.DateTimeField(null=True, verbose_name='最后一次登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('avatar_file', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.File')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(to='app.User'),
        ),
        migrations.AddField(
            model_name='permission',
            name='roles',
            field=models.ManyToManyField(to='app.Role'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
