# Generated by Django 2.0.6 on 2018-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('salt', models.CharField(max_length=5, verbose_name='密码随机字符串加密')),
                ('lasted_at', models.DateTimeField(null=True, verbose_name='最后一次登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
