# Generated by Django 2.0.6 on 2018-06-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180629_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
    ]
